version: '3.8'
services:
  config-server:
    image: ghcr.io/projectalexandria/config-server:main
    volumes:
      - "config:/config/" # not readonly, because new configs are automatically added.


volumes:
  config: {}